import Navigation from '@/components/Navigation'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex min-h-screen max-w-4xl mx-auto mt-4'>
          <div className='grid grid-cols-3 gap-4 w-full'>
            <div className='sticky top-0'>
              <Navigation />
            </div>
            <div className='col-span-2'>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
